# Generated by Django 5.1.1 on 2024-09-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
